ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 广告拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 Telegram,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=💬 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=💬 AI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=📹 YouTube,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 哔哩哔哩,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 FALLBACK,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=📲 Telegram`select`[]🇭🇰 香港
custom_proxy_group=💬 AI`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇨🇳 台湾`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🚀 手动切换
custom_proxy_group=📹 YouTube`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🚀 手动切换
custom_proxy_group=📺 哔哩哔哩`select`[]🎯 全球直连`[]🇨🇳 台湾`[]🇭🇰 香港
custom_proxy_group=🍎 苹果服务`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 FALLBACK`select`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 香港`[]🇨🇳 台湾`[]🇰🇷 韩国`[]🇸🇬 新加坡`[]🇯🇵 日本`[]🇺🇲 美国`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🇭🇰 香港`url-test`(港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本`url-test`(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|JP|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国`url-test`(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇨🇳 台湾`url-test`(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇸🇬 新加坡`url-test`(新加坡|坡|狮城|SG|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇰🇷 韩国`url-test`(KR|Korea|KOR|首尔|韩|韓)`http://www.gstatic.com/generate_204`300,,50
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
add_emoji=true
remove_old_emoji=true
skip_cert_verify_flag=true
clash_use_new_field_name=true
write_managed_config=false
udp_flag=false

exclude_remarks=(续费|重置|推广|佣金|IPV6接入|TG群|到期|Update|Traffic|更新订阅|更新一次订阅|不一定|勒索|通告|均为二手倒卖|重大漏洞|公告|已恢复|炸了|Expire|时间|Panel|用户群|学术|登录|面板|计划|全局代理|剩余流量|异常|custom)

emoji=(Channel|Website),⚫︎
rename=.*(香港|亚服游戏|亚服防失联|中港|深港IEPL|深港专线 ⁴ˣ|广港|莞港|海港|苏港|湘港|杨港|安港|永久虚通路连接|港鱼蛋粉|港鸡蛋仔|AnyPath®|HK|hk|HONG KONG|Hong Kong|HONGKONG|Hongkong|HongKong).*@🇭🇰 香港 | HKG
rename=.*(台湾|台灣|台北|台中|新北|彰化|深港专线转台湾|冀台|沪台|浙台|深台|湘台|珠台|苏台|闽台|广台|回国|tw|Taipei|Kaohsiung|TW|TPE|Taiwan|TAIPEI|TAIWAN|Tai Wan|Tai wan).*@🇨🇳 台湾 | TWN
rename=.*(新加坡|[狮獅]城|新坡|广新|浙新|杨新|安新|海新|SG|sg|SINGAPORE|Singapore).*@🇸🇬 新加坡 | SGP
rename=.*(日本|日-本|东京|大阪|埼玉|名古屋|沪日|日服|广日|杭日|京日|JP|jp|TOKYO|Tokyo|Osaka|Fukuoka|Nagoya|JAPAN|KIX|Saitama|Japan).*@🇯🇵 日本 | JPN
rename=.*(美[国國]|广美|美西|华盛顿|波特兰|达拉斯|俄勒冈|凤凰城|菲尼克斯|费利蒙|弗里蒙特|硅谷|旧金山|弗吉尼亚|拉斯维加斯|洛杉|圣何塞|圣荷西|圣塔?克拉拉|西雅图|芝加哥|哥伦布|纽约|阿什本|丹佛|加利福尼亚|亚特兰大|us|UNITED STATES|EWR|Newark|SJC|LAX|SEA|CMH|SANJOSE|Washington|Portland|Dallas|Oregon|Phoenix|Fremont|Valley|Francisco|Vegas|Los[^a-z]*Angeles|San[^a-z]*Jose|Santa[^a-z]*Clara|Seattle|Chicago|Columbus|York|Ashburn|US|UNITEDSTATES|United States).*@🇺🇲 美国 | USA
rename=.*(安道尔|Andorra).*@🇦🇩 安道尔 | AND
rename=.*(阿根廷|Argentina|ARG|AR).*@🇦🇷 阿根廷 | ARG
rename=.*(阿联酋|迪拜|阿布扎比|阿拉伯联合酋长国|Dubai|AE|United Arab Emirates).*@🇦🇪 阿联酋 | ARE
rename=.*(阿富汗|Afghanistan).*@🇦🇫 阿富汗 | AFG
rename=.*(阿尔巴尼亚|Albania).*@🇦🇱 阿尔巴尼亚 | ALB
rename=.*(亚美尼亚|Armenia).*@🇦🇲 亚美尼亚 | ARM
rename=.*(安哥拉|Angola).*@🇦🇴 安哥拉 | AGO
rename=.*(澳大利亚|澳洲|悉尼|墨尔本|AU|Australia|Sydney).*@🇦🇺 澳大利亚 | AUS
rename=.*(阿鲁巴|Aruba).*@🇦🇼 阿鲁巴 | ABW
rename=.*(阿塞拜疆|Azerbaijan).*@🇦🇿 阿塞拜疆 | AZE
rename=.*(波黑|波斯尼亚和黑塞哥维那|Herzegovina).*@🇧🇦 波黑 | BIH
rename=.*(巴巴多斯|Barbados).*@🇧🇧 巴巴多斯 | BRB
rename=.*(孟加拉|Bangladesh).*@🇧🇩 孟加拉 | BGD
rename=.*(比利时|比利時|BE|Belgium).*@🇧🇪 比利时 | BEL
rename=.*(保加利亚|Bulgaria).*@🇧🇬 保加利亚 | BGR
rename=.*(巴林|Bahrain).*@🇧🇭 巴林 | BHR
rename=.*(百慕大|Bermuda).*@🇧🇲 百慕大 | BMU
rename=.*(文莱|Brunei).*@🇧🇳 文莱 | BRN
rename=.*(玻利维亚|Bolivia).*@🇧🇴 玻利维亚 | BOL
rename=.*(巴西|圣保罗|São Paulo|S?o Paulo|BR|Brazil).*@🇧🇷 巴西 | BRA
rename=.*(巴哈马|Bahamas).*@🇧🇸 巴哈马 | BHS
rename=.*(不丹|Bhutan).*@🇧🇹 不丹 | BTN
rename=.*(白俄罗斯|Belarus).*@🇧🇾 白俄罗斯 | BLR
rename=.*(伯利兹|Bolize).*@🇧🇿 伯利兹 | BLZ
rename=.*(加拿大|蒙特利尔|温哥华|多伦多|Montréal|Vancouver|Toronto|YYZ|CA|Canada).*@🇨🇦 加拿大 | CAN
rename=.*(瑞士|Switzerland|CH).*@🇨🇭 瑞士 | CHE
rename=.*(智利|Santiago|Chile|CL).*@🇨🇱 智利 | CHL
rename=.*(哥伦比亚|圣地亚哥|Colombia).*@🇨🇴 哥伦比亚 | COL
rename=.*(哥斯达黎加|Costa Rica|CR).*@🇨🇷 哥斯达黎加 | CRI
rename=.*(库拉索|Curacao).*@🇨🇼 库拉索 | CUW
rename=.*(塞浦路斯|Cyprus).*@🇨🇾 塞浦路斯 | CYP
rename=.*(捷克|布拉格|Czech).*@🇨🇿 捷克 | CZE
rename=.*(德国|法兰克福|京德游戏|FI|Frankfurt|DE|Germany).*@🇩🇪 德国 | DEU
rename=.*(吉布提|Djibouti).*@🇩🇯 吉布提 | DJI
rename=.*(丹麦|哥本哈根|DNK|DK|Danmark|Denmark).*@🇩🇰 丹麦 | DNK
rename=.*(阿尔及利亚|Algeria).*@🇩🇿 阿尔及利亚 | DZA
rename=.*(厄瓜多尔|Ecuador).*@🇪🇨 厄瓜多尔 | ECU
rename=.*(爱沙尼亚|Estonia).*@🇪🇪 爱沙尼亚 | EST
rename=.*(埃及|开罗|EGP|Egypt).*@🇪🇬 埃及 | EGY
rename=.*(西班牙|马德里|ESP|Madrid|Spain).*@🇪🇸 西班牙 | ESP
rename=.*(芬兰|芬蘭|Finland|FL).*@🇫🇮 芬兰 | FIN
rename=.*(法国|巴黎|Marseille|CDG|Paris|FR|France).*@🇫🇷 法国 | FRA
rename=.*(英国|英|伦敦|UK|GB|LHR|London|England|Britain|Kingdom).*@🇬🇧 英国 | GBR
rename=.*(格鲁吉亚|Georgia).*@🇬🇪 格鲁吉亚 | GEO
rename=.*(加纳|Ghana).*@🇬🇭 加纳 | GHA
rename=.*(格陵兰|GRL|Greenland).*@🇬🇱 格陵兰 | GRL
rename=.*(希腊|希臘|雅典|GRC|Greece).*@🇬🇷 希腊 | GRC
rename=.*(危地马拉|Guatemala|GT).*@🇬🇹 危地马拉 | GTM
rename=.*(克罗地亚|Croatia).*@🇭🇷 克罗地亚 | HRV
rename=.*(匈牙利|Hungary).*@🇭🇺 匈牙利 | HUN
rename=.*(印度尼西亚|印尼|雅加达|IDN|Indonesia).*@🇮🇩 印度尼西亚 | IDN
rename=.*(爱尔兰|愛爾蘭|都柏林|Ireland).*@🇮🇪 爱尔兰 | IRL
rename=.*(以色列|耶路撒冷|ISL|ISR|IL|Israel).*@🇮🇱 以色列 | ISR
rename=.*(马恩岛|Isle of Man).*@🇮🇲 马恩岛 | IMN
rename=.*(伊朗|Iran).*@🇮🇷 伊朗 | IRN
rename=.*(冰岛|冰島|雷克雅未克|Iceland).*@🇮🇸 冰岛 | ISL
rename=.*(意大利|米兰|拉齐奥|佛罗伦萨|Milan|Rome|IT|Italy).*@🇮🇹 意大利 | ITA
rename=.*(印度|孟买|新德里|加尔各答|Mumbai|IND|India).*@🇮🇳 印度 | IND
rename=.*(泽西岛|Jersey).*@🇯🇪 泽西岛 | JEY
rename=.*(约旦|Jordan).*@🇯🇴 约旦 | JOR
rename=.*(肯尼亚|Kenya).*@🇰🇪 肯尼亚 | KEN
rename=.*(吉尔吉斯斯坦|Kyrgyzstan).*@🇰🇬 吉尔吉斯斯坦 | KGZ
rename=.*(柬埔寨|金边|Kampuchea|Cambodia).*@🇰🇭 柬埔寨 | KHM
rename=.*(开曼群岛|Cayman Islands).*@🇰🇾 开曼群岛 | CYM
rename=.*(科索沃|Kosovo).*@🇽🇰 科索沃 | XKS
rename=.*(韩国|韩|韓|首尔|KR|KOR|kr|CHUNCHEON|春川|大版|Seoul|ICN|Chuncheon|Korea).*@🇰🇷 韩国 | KOR
rename=.*(哈萨克斯坦|哈薩克斯坦|努尔苏丹|KZ|Kazakhstan).*@🇰🇿 哈萨克斯坦 | KAZ
rename=.*(老挝|Laos).*@🇱🇦 老挝 | LAO
rename=.*(列支敦士登|Liechtenste).*@🇱🇮 列支敦士登 | LIE
rename=.*(斯里兰卡|Sri Lanka).*@🇱🇰 斯里兰卡 | LKA
rename=.*(立陶宛|Lithuania|LT).*@🇱🇹 立陶宛 | LTU
rename=.*(卢森堡|盧森堡|LU FranTech|LU|Luxembourg).*@🇱🇺 卢森堡 | LUX
rename=.*(利比亚|Libya).*@🇱🇾 利比亚 | LBY
rename=.*(澳门|澳門|MAC|MTel|MO|Macao|Macau).*@🇲🇴 澳门 | MAC
rename=.*(摩洛哥|Morocco).*@🇲🇦 摩洛哥 | MAR
rename=.*(摩纳哥|Monaco).*@🇲🇨 摩纳哥 | MCO
rename=.*(摩尔多瓦|Moldova|MD).*@🇲🇩 摩尔多瓦 | MDA
rename=.*(黑山|Montenegro).*@🟇🇪 黑山 | MNE
rename=.*(北马其顿|Macedonia).*@🇲🇰 北马其顿 | MKD
rename=.*(缅甸|Myanmar|Burma).*@🇲🇲 缅甸 | MMR
rename=.*(蒙古|Mongolia).*@🇲🇳 蒙古 | MNG
rename=.*(马耳他|Malta).*@🇲🇹 马耳他 | MLT
rename=.*(毛里求斯|Mauritius).*@🇲🇺 毛里求斯 | MUS
rename=.*(墨西哥|MEX|Mexico).*@🇲🇽 墨西哥 | MEX
rename=.*(马来西亚|马来|大马|MYS|Malaysia).*@🇲🇾 马来西亚 | MYS
rename=.*(尼日利亚|NG|Nigeria).*@🇳🇬 尼日利亚 | NGA
rename=.*(荷兰|阿姆斯特丹|NLD|AMS|NL|SC|Netherlands).*@🇳🇱 荷兰 | NLD
rename=.*(挪威|Norway).*@🇳🇴 挪威 | NOR
rename=.*(尼泊尔|NP|Nepal).*@🇳🇵 尼泊尔 | NPL
rename=.*(新西兰|新西蘭|NZL|NZ|New Zealand).*@🇳🇿 新西兰 | NZL
rename=.*(阿曼|Oman).*@🇴🇲 阿曼 | OMN
rename=.*(巴拿马|PAN|Panama).*@🇵🇦 巴拿马 | PAN
rename=.*(秘鲁|Peru).*@🇵🇪 秘鲁 | PER
rename=.*(菲律宾|马尼拉|PH|Philippines).*@🇵🇭 菲律宾 | PHL
rename=.*(巴基斯坦|Pakistan).*@🇵🇰 巴基斯坦 | PAK
rename=.*(波兰|波蘭|POL|PL|Poland).*@🇵🇱 波兰 | POL
rename=.*(奥地利|奧地利|AT|Austria).*@🇦🇹 奥地利 | AUT
rename=.*(波多黎各|Puerto).*@🇵🇷 波多黎各 | PRI
rename=.*(葡萄牙|Portugal).*@🇵🇹 葡萄牙 | PRT
rename=.*(巴拉圭|Paraguay).*@🇵🇾 巴拉圭 | PRY
rename=.*(卡塔尔|Qatar).*@🇶🇦 卡塔尔 | QAT
rename=.*(留尼汪|Reunio).*@🇷🇪 留尼汪 | REU
rename=.*(罗马尼亚|Romania).*@🇷🇴 罗马尼亚 | ROU
rename=.*(塞尔维亚|Serbia).*@🇷🇸 塞尔维亚 | SRB
rename=.*(俄罗斯|伯力|莫斯科|圣彼得堡|西伯利亚|毛子|Moscow|RU|Russia).*@🇷🇺 俄罗斯 | RUS
rename=.*(卢旺达|Rwanda).*@🇷🇼 卢旺达 | RWA
rename=.*(沙特阿拉伯|沙特|Saudi Arabia).*@🇸🇦 沙特阿拉伯 | SAU
rename=.*(瑞典|Stockholm|Sweden|SE).*@🇸🇪 瑞典 | SWE
rename=.*(斯洛文尼亚|Slovenia).*@🇸🇮 斯洛文尼亚 | SVN
rename=.*(斯洛伐克|Slovensko|SK|Slovakia).*@🇸🇰 斯洛伐克 | SVK
rename=.*(朝鲜|KP|DPK|North Korea).*@🇰🇵 朝鲜 | PRK
rename=.*(泰国|曼谷|泰國|THA|TH|Thailand|TH 01).*@🇹🇭 泰国 | THA
rename=.*(突尼斯|Tunisia).*@🇹🇳 突尼斯 | TUN
rename=.*(土耳其|伊斯坦布尔|TUR|Turkey|TR).*@🇹🇷 土耳其 | TUR
rename=.*(乌兹别克|Uzbekistan).*@🇺🇿 乌兹别克 | UZB
rename=.*(梵蒂冈|VAT|Vatican).*@🇻🇦 梵蒂冈 | VAT
rename=.*(委内瑞拉|Venezuela).*@🇻🇪 委内瑞拉 | VEN
rename=.*(越南|VN|Vietnam).*@🇻🇳 越南 | VNM
rename=.*(乌克兰|基辅|Ukraine).*@🇺🇦 乌克兰 | UKR
rename=.*(乌拉圭|Uruguay).*@🇺🇾 乌拉圭 | URY
rename=.*(英属维尔京群岛|British Virgin Islands).*@🇻🇬 英属维尔京群岛 | VGB
rename=.*(美属维尔京群岛|U.S. Virgin Islands).*@🇻🇮 美属维尔京群岛 | VIR
rename=.*(也门|Yemen).*@🇾🇪 也门 | YEM
rename=.*(南非|Johannesburg|ZA|South Africa).*@🇿🇦 南非 | ZAF
rename=.*(南极|Antarctica|AQ|ATA).*@🇦🇶 南极 | ATA
rename=.*(古巴|CUB|Cuba).*@🇨🇺 古巴 | CUB
rename=.*(马尔代夫|Maldives).*@🇲🇻 马尔代夫 | MDV
rename=.*(关岛|Guam).*@🇬🇺 关岛 | GUM
rename=.*(斐济|Fiji).*@🇫🇯 斐济 | FJI
rename=.*(巴勒斯坦|Palestine).*@🇵🇸 巴勒斯坦 | PSE
rename=.*(东帝汶|Timor-Leste|East Timor).*@🇹🇱 东帝汶 | TLS
rename=.*(黎巴嫩|Lebanon).*@🇱🇧 黎巴嫩 | LBN
rename=.*(伊拉克|Iraq).*@🇮🇶 伊拉克 | IRQ
rename=.*(叙利亚|Syria).*@🇸🇾 叙利亚 | SYR
rename=.*(科威特|Kuwait|KW).*@🇰🇼 科威特 | KWT
rename=.*(土库曼斯坦|Turkmenistan).*@🇹🇲 土库曼斯坦 | TKM
rename=.*(汤加|Tonga).*@🇹🇴 汤加 | TON
rename=.*(所罗门群岛|Solomon Islands).*@🇸🇧 所罗门群岛 | SLB
rename=.*(巴布亚新几内亚|Papua New Guinea).*@🇵🇬 巴布亚新几内亚 | PNG
rename=.*(直布罗陀|Gibraltar).*@🇬🇮 直布罗陀 | GIB
rename=.*(圣马力诺|San Marino).*@🇸🇲 圣马力诺 | SMR
rename=.*(法罗群岛|Faroe Islands).*@🇫🇴 法罗群岛 | FRO
rename=.*(奥兰群岛|Åland Islands).*@🇦🇽 奥兰群岛 | ALA
rename=.*(海地|Haiti).*@🇭🇹 海地 | HTI
rename=.*(牙买加|Jamaica).*@🇯🇲 牙买加 | JAM
rename=.*(苏里南|Suriname).*@🇸🇷 苏里南 | SUR
rename=.*(法属圭亚那|French Guiana).*@🇬🇫 法属圭亚那 | GUF
rename=.*(特立尼达和多巴哥|Trinidad and Tobago).*@🇹🇹 特立尼达和多巴哥 | TTO
rename=.*(洪都拉斯|Honduras).*@🇭🇳 洪都拉斯 | HND
rename=.*(尼加拉瓜|Nicaragua).*@🇳🇮 尼加拉瓜 | NIC
rename=.*(多米尼克|Dominica).*@🇩🇲 多米尼克 | DMA
rename=.*(多米尼加|Dominican Republic).*@🇩🇴 多米尼加 | DOM
rename=.*(多哥|Togo).*@🇹🇬 多哥 | TGO
rename=.*(贝宁|Benin).*@🇧🇯 贝宁 | BEN
rename=.*(马里|Mali).*@🇲🇱 马里 | MLI
rename=.*(刚果|Congo|DRC|Kinshasa).*@🇨🇩 刚果 | COD
rename=.*(佛得角|Cabo Verde|Cape Verde).*@🇨🇻 佛得角 | CPV
rename=.*(喀麦隆|Cameroon).*@🇨🇲 喀麦隆 | CMR
rename=.*(莫桑比克|Mozambique).*@🇲🇿 莫桑比克 | MOZ
rename=.*(科特迪瓦|Côte d'Ivoire|Ivory Coast).*@🇨🇮 科特迪瓦 | CIV
rename=.*(斯威士兰|Eswatini|Swaziland).*@🇸🇿 斯威士兰 | SWZ
rename=.*(坦桑尼亚|Tanzania).*@🇹🇿 坦桑尼亚 | TZA
rename=^[a-z0-9].*@🏴‍☠️ 未知地区 | Unknown
rename=.*(节点|防丢|TG).*@🏴‍☠️ 未知地区 | Unknown
